### ISSUE TITLE
マーカー以外のマップをクリックした時の処理追加

### ISSUE THREAD

**Issue by sho25** [torimons/torimon#210]
### Description
- SpotInfoを不可視にする
- focusedSpotの更新前にfocusedSpotになっていたSpotを選択されていない色に変更する

**Comment by shuto410** [comment]
そもそものfocusedSpotマーカーの色を変えるタスクはここでやる予定ありますか

**Comment by sho25** [comment]
やる予定です

**Comment by shuto410** [comment]
了解です
