### ISSUE TITLE
Herokuの調査

### ISSUE THREAD

**Issue by kenchalros** [torimons/torimon#3]
コスト: 2
- 無料枠でどこまでできるのか
- mongoDB、Node.js(Express), Vue.jsなど使えるかどうか

**Comment by sho25** [comment]
## 調査内容

- [ ]  無料枠でどこまでできるのか
- [x]  mongoDB，Node.js(Express)，Vue.jsなど使えるかどうか

## 利用可能
- mongoDB
- Node.js(Express)
- Vue.js(Express)

## 無料枠
- 調査中

## 参考記事
- [Node.js(Express) 事始め ＆ Heroku へデプロイまでのメモ](https://qiita.com/hkusu/items/e46de8c446840c50aefe))

**Comment by shuto410** [comment]
記事を読んだけど．Herokuの方で環境構築（もしくはテンプレート選択）みたいなフェーズはないの？関連記事でSheedとやらのリポジトリはクローンしてたみたいだけど

**Comment by sho25** [comment]
@shuto410 
関連記事のSheed(getting-started?)はすでに出来上がってるやつをテストデプロイしてるだけだと思う
herokuのremoteにpushするとprocfileとかrequirements.txtみたいなのをheroku側が自動的に見て必要パッケージとかをインストールしてくれるはず
