### ISSUE TITLE
スポットのポリゴンプロパティをnotionの総合学習プラザ.jsonに追加する

### ISSUE THREAD

**Issue by shuto410** [torimons/torimon#38]
追加しました↓
https://www.notion.so/json-f98f6ffd1fd246a6b298bb29e923272d

geojson形式で

**Comment by kenchalros** [comment]
typeとcoordinatesだけを持つようになっているけど、properties（線の太さとかopacityの情報を持つ）はなくてもいい？（現状はなくても問題なさそう）
