### ISSUE TITLE
issueテンプレート更新

### ISSUE THREAD

**Issue by shuto410** [torimons/torimon#65]
### Description
こんな感じでお願いします

**Comment by ooka-hidenori** [comment]
質問なのですが、これをするにあたってbranchは新しく作るべきですか？それとも、第2Sprintで使用したbranchを使うべきですか？
あと、更新が必要になった理由を再度教えてもらってもいいですか。

**Comment by shuto410** [comment]
branchに関してはどちらでも構いませんが、古い方はマージが必要なので新しく切った方が楽だと思います
更新の理由は、見出しのサイズの大きさやissue番号書く箇所の見出し文の長さのせいでprojectsのかんばんでissueを見る際に少し見辛いと思ったためです
上の例に関しては、自然な日本語で短くすることが出来なかったので英語に統一してみました
