### ISSUE TITLE
ズームレベルによって切り替わる表示レベルをvuexストアに追加

### ISSUE THREAD

**Issue by kenchalros** [torimons/torimon#75]
### Description
ズームレベルに応じて二段階に切り替わる表示レベルをstateに用意する
そのgetterとmutationを作る

**Comment by shuto410** [comment]
現状focusedMapIdはフォーカスされているスポットを特定するために利用されることを想定しているので，何かしら分けた方が良さそう

**Comment by kenchalros** [comment]
ふむふむ．現在使用中のマップを表す何かを用意した方がいいんですね．

**Comment by shuto410** [comment]
そうですね，あとfocusedSpot: {spotId: number, mapId: number}とかにしてfocusedMapIdは明け渡してもいい

**Comment by shuto410** [comment]
後どの階層を見ているのかの情報の保持との兼ね合いも気になる

**Comment by kenchalros** [comment]
確かに〜。もうちょっと考えたほうがいいですね…。
