### ISSUE TITLE
仮地図データを作成する

### ISSUE THREAD

**Issue by kenchalros** [torimons/torimon#8]
コスト: 2
- ウエスト2号館の3階までのデータ作成 -> 対象を総合学習プラザに変更
- 地図画像の作成

**Comment by shuto410** [comment]
学習プラザの地図
https://www.notion.so/567e79eb752e4160ae4d4daba534192c

**Comment by kenchalros** [comment]
部屋の緯度と経度，階層をテーブルに追加しました．（トイレと階段は入れてないです）

**Comment by kenchalros** [comment]
https://www.notion.so/json-f98f6ffd1fd246a6b298bb29e923272d
仮データ作成しました．（正確な地図ではありません！）

**Comment by kenchalros** [comment]
https://www.notion.so/json-f98f6ffd1fd246a6b298bb29e923272d
mapがspot_ids, node_idsを持つのではなく，spot, node, edgeを直接持つように変更しました．
